### PR TITLE
Feat / no-pack flag

### PR DESCRIPTION
**Pull request by andirsun**
Closes https://github.com/saltyshiomix/nextron/issues/251

### CODE REVIEW

**Comment by andirsun** [comment]
@saltyshiomix ??

**Comment by Psycokwet** [comment]
Hello :)
Thank you for your proposal, could you please briefly explain what's the purpose of this pull request? I'm not yet qualified in this kind of things.

**Comment by andirsun** [comment]
@m5x5 please review this.

**Review by saltyshiomix — APPROVED** [review]
Sorry for late reply.

It will be useful as you mentioned #251 💯 

LGTM <3

**Comment by saltyshiomix** [comment]
@andirsun 

Nextron v8.2.0 is out which includes your PR 🎉 

Thank you for your efforts and kindness.

**Pull request merged**
