### PR TITLE
[feat] Added electron options to run in wsl environment

### PR DESCRIPTION
**Pull request by shkim4936**
* Added option to run x window virtually in windows wsl environment.
* --no-sandbox, --disable-features
* Run on wsl: nextron --no-sandbox true --disable-features VizDisplayCompositor

### CODE REVIEW

**Comment by saltyshiomix** [comment]
@shkim4936 

Could you try command line switches?

Electron provides switches that Chromium uses:

```js
// in `background.js`
// note: we must use these options before `app` is ready
app.commandLine.appendSwitch('--no-sandbox');
app.commandLine.appendSwitch('--disable-features', 'VizDisplayCompositor');
```

**Comment by saltyshiomix** [comment]
Further infomation:

- https://electronjs.org/docs/api/command-line
- https://github.com/electron/electron/blob/master/docs/api/command-line-switches.md

**Comment by shkim4936** [comment]
It works! Thank you 👍

**Comment by ben-styling** [comment]
@shkim4936 
Why was this closed and not merged? 
I can make the changes to prevent this from being applied in production if that was why?

**Comment by lacymorrow** [comment]
@ben-styling Have you tried using the Electron command-line switches? We would rather not adopt flags for every available option and instead prefer using `app` switches.

**Pull request closed without merging**
