### PR TITLE
chore: Update collaborators

### PR DESCRIPTION
**Pull request by saltyshiomix**
Thanks a lot 👍 #410

### CODE REVIEW

**Comment by bm777** [comment]
@saltyshiomix Thanks, we (@FranciscoJBrito and I) will push on this branch.

**Review by bm777 — COMMENTED** [review]
Thks  @saltyshiomix  :)

**Review by bm777 — COMMENTED** [review]
Reviewed for a 2nd time.

**Comment by saltyshiomix** [comment]
@bm777 Thanks,

**Pull request merged**
