### PR TITLE
Add Basic js python example

### PR DESCRIPTION
**Pull request by bm777**
## Description
This PR adds a Python example on top of basic-lang-javascript.  We identified the need for this feature in response to some user feedback specifically in #427. It is described and commented on.

### Files added:
1. `scripts/runner.sh` -> to run python file (The user can also run python directly via the exec child-process)
2. `scripts/main.py` -> Python script that the user wants to execute.

### Modification
 - added directly the main/ folder into the example folder because of some modification in the `basic-js-python/main/background.js` file which is different from the `_template/js/main/background.js`. Just to avoid some mix in the dev.js to manage or orchestrate the creation of the Nextron project via the `example` command.

https://github.com/saltyshiomix/nextron/assets/29865600/3cb36121-dd76-44ca-9021-9089fce5165f

### CODE REVIEW

**Comment by bm777** [comment]
This cannot be merged, because it is not configured as you did for js.
@saltyshiomix

**Comment by saltyshiomix** [comment]
@bm777

Sorry for late reply.

It works fine even if production build!

I'll merge it after some fixes :)

**Comment by bm777** [comment]
:)

**Review by saltyshiomix — APPROVED** [review]
LGTM <3

**Pull request merged**
