### PR TITLE
cross-spawn to dependencies

### PR DESCRIPTION
**Pull request by bkniffler**

### CODE REVIEW

**Comment by mittoa** [comment]
@bkniffler

Please let me know why.
Nextron has already `cross-spawn` via `node-npx` wrapper.

**Comment by bkniffler** [comment]
Because every package should declare what they need instead of relying on other packages, at least as a peerDependency if for some reason you're not comfortable with that. 

PNPM, which is getting more traction, does for example currently throw errors with nextron.

**Comment by saltyshiomix** [comment]
@bkniffler 

Thank you for your advices!
It is reasonable enough to fix nextron.
I'll update nextron as soon as possible :)

**Comment by saltyshiomix** [comment]
@bkniffler 

Thank you for your PR 👍

**Comment by bkniffler** [comment]
Thanks for your efforts, keep it up!

**Comment by saltyshiomix** [comment]
@bkniffler 

I'll publish next `nextron` which includes this PR 👍

**Comment by saltyshiomix** [comment]
@bkniffler 

Just published `nextron@5.10.2` which includes your PR :)

**Pull request merged**
